### ISSUE TITLE
Consider partitioning tests for behavior, bug fixes, exceptions, etc

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-Java-unit-test#67]
The larger test modules are a mess of different tests. Partitioning may make them easier to sort through.

**Comment by johnjaylward** [comment]
I'm not sure if you've seen [TestNG ](http://testng.org/doc/ )before, but I really like how it handles tests cases.

For example, this is what one of my test cases looks like for a section of my excel reader that parses the values in the header for column names:

```java
public class ColumnReadHelperTest {
    /**
     * @return data for testing
     */
    @DataProvider
    private static String[][] sanitizeColumnNameData() {
        return new String[][] {
            {
                null, ""
            }, {
                "", ""
            }, {
                "BOB", "bob"
            }, {
                "BoB", "bob"
            }, {
                "   BOB   ", "bob"
            }, {
                "   B_O B   ", "b o b"
            }, {
                "   BOB__   ", "bob"
            }, {
                "   BO  B   ", "bo b"
            }, {
                "   BO   B   ", "bo b"
            }, {
                "   BO ___ ---   B   ", "bo b"
            }, {
                "   B--___OB_   ", "b ob"
            }, {
                "      ", ""
            }, {
                "_______________", ""
            }, {
                "---------------", ""
            }, {
                "_ -_ -_ -_ -_ -_ -_ -_ ", ""
            }, {
                "123", "123"
            }, {
                "AbCd123", "abcd123"
            }, {
                " - _ AbCd123 _ - ", "abcd123"
            }
        };
    }

    /**
     * @param s
     *            string to convert
     * @param expected
     *            expected result
     */
    @Test(dataProvider = "sanitizeColumnNameData",
            timeOut = 1)
    public void sanitizeColumnName(final String s, final String expected) {
        final String actual = ColumnReadHelper.sanitizeColumnName(s);
        assert actual.equals(expected) : "Expected : [" + expected + "] but got: [" + actual + "]";
    }

    /**
     * Initializes the class we are using to ensure all static fields are constructed before calling
     * the tests. This will help ensure timing of the tests is not effected by "startup costs" for
     * the class.
     */
    @BeforeClass
    private void init() {
        ColumnReadHelper.sanitizeColumnName("a");
    }
}
```

TestNG converts the dataProvider into the parameters that the actual test uses. Each set of parameters is run as a single test so it will run every set of data even if the first one fails. I find that it makes finding and fixing bugs a lot easier. i.e in my test above if the first parameter set `{ null, "" }` errored (NPE, or the expected value didn't match) then TestNG would just flag that single data item as a fail and move onto the next one: `{ "", "" }`

It supports all the JUnit Assert functions and it has it's own versions of most of them too (I just dislike using them, for some reason I like using actual asserts directly... mostly because the assert keyword pops up in my syntax highlighter)

It also allows you to assign tests to groups ("Regression", "Bug", etc). My test annotation could have looked like this for example:
```java
@Test(dataProvider = "sanitizeColumnNameData",
            timeOut = 1, groups = {"group1", "Another Group"})
```

TestNG does have some performance test options (like that timeout one I have in my test) but it's not really made for formal performance testing.

Anyway just my 2cents.

**Comment by johnjaylward** [comment]
Oh, here's an example of what that test run looks like when run in Eclipse and has no failures.
![image](https://cloud.githubusercontent.com/assets/383703/26252680/ebb7f04a-3c7e-11e7-9f9d-2d8ddcc82c90.png)

**Comment by stleary** [comment]
Thanks, have never used testng, will look into it.

**Comment by mouyang** [comment]
I completely support the use of TestNG for the reasons described above.  However, I think the benefits gained from it will be limited and not immediately obvious while test strings are still embedded in the Java source.

**Comment by stleary** [comment]
Not prioritized
